
[operator]

# URL of the node to interact with the blockchain.
node_url = ...

# Used port where the operator listens
# port = 3000 # optional

[operator.workspace.jwt]

# JWT secret used to authenticate users when interacting with the Workspace API.
# secret = ... # optional

# Validity of the JWT secret
# tokenValidity = "8h" # optional

[operator.workspace.graphql]

# Enable graphql debug mode.
# debug = true # optional

[operator.swagger]
# path = "swagger" # optional

[operator.cors]
# origin = "*" # optional
# methods = "GET,POST,PUT,DELETE,OPTIONS" # optional

[operator.database.encryption]
# algorithm = "chacha20-poly1305" # optional
# iv_length = 12 # optional
# encryption_key = ... # optional
# allow_encryption_key_generation = true # optional

[operator.database.postgresql]
user = ...
password = ...
database = ...
url = ...
port = ...

[operator.database.mysql]
user = ...
password = ...
database = ...
url = ...
port = ...

[operator.database.sqlite]
database = ...

[operator.protocols.wap]
# version = "v0" # optional

[operator.paths]
# home = "/home/gamarcadet/git/carmentis-operator/operator" # optional
# init_token = "admin-token.txt" # optional

# Path where database encryption key is stored.
# db_encryption_key = "db-encryption-key.txt" # optional
# jwt_secret = "jwt-secret.txt" # optional
