[operator]
# URL of the node used by the operator to anchor information on chain
node_url = "http://localhost:26657"
# used port (default)
port = 3000

[operator.workspace.jwt]
# secret key and token validity for JWT
secret = "supersecretjwtkey" # (optional)
tokenValidity = "8h" # (default)

[operator.workspace.graphql]
# graphql-related config
debug = true # (default)

[operator.swagger]
# swagger-related config
path = "swagger" # (default)

[operator.cors]
# cors-related config
origin = "*" # (default)
methods = "GET,POST,PUT,DELETE,OPTIONS" # (default)

[operator.database.encryption]
# configuration of the encryption
algorithm = "chacha20-poly1305" # (default)
iv_length = 12 # (default)
# Optional encryption key; when absent, it may be generated automatically
encryption_key = "my-secret-encryption-key" # (optional)
# When allowed, an encryption key is generated automatically.
# Be careful, when the encryption key is changed, encrypted data cannot be decrypted by the server anymore.
allow_encryption_key_generation = true # (default)

# Choose one of the following database sections depending on the backend you want:

#[operator.database.postgresql] # (optional)
#user = "postgres"
#password = "example"
#database = "mydb"
#url = "localhost"
#port = 5432

#[operator.database.mysql] # (optional)
#user = "root"
#password = "example"
#database = "mydb"
#url = "localhost"
#port = 3306

#[operator.database.sqlite] # (optional)
# SQLite database file is stored relatively to the paths.home location.
#database = "data.sqlite"

[operator.protocols.wap]
# Wallet Authentication Protocol (WAP): Used to obtain wallet information and signature.
version = "v0" # (default)

[operator.paths]
# By default, all paths are relative to the paths.home location.
home = "/var/lib/myapp" # (default: current working directory)
init_token = "admin-token.txt" # (default)
db_encryption_key = "db-encryption-key.txt" # (default)
